enum SectionVariant {
  // These are examples and can be changed
  STARTSCREEN,
  MAINMENU,
  CHOOSECHARACTER,
  ENTERNAME,
  GAMESETTINGS,
  CHOOSEDIFFICULTY,
  TUTORIAL,
  GAMELEVELS,
  GAMEOVER,
  LEADERBOARD,
  ENDGAME;
}
