enum SectionVariant {
  // These are examples and can be changed
  STARTSCREEN,
  CHOOSECHARACTER,
  ENTERNAME,
  CHOOSETUTORIAL,
  CHOOSEDIFFICULTY,
  GAMELEVELS,
  GAMEOVER,
  LEADERBOARD,
  ENDGAME;
}
